### ISSUE TITLE
BalloonStyle not supported

### ISSUE THREAD

**Issue by bugfindr** [Raruto/leaflet-kmz#13]
@Raruto Can you please add code to support to BalloonStyle tag?  :)

**Comment by Raruto** [comment]
Hi bugfindr,
I think you are referring to the [\<BalloonStyle\>](https://developers.google.com/kml/documentation/kmlreference#balloonstyle) tag.

If you are interested in seeing new features supported I kindly suggest you start studying the library code and propose your own solutions ([here](https://github.com/Raruto/leaflet-kmz/issues/11#issuecomment-669612399) you can see a simple example on how to extend it).

In order to disable the default balloons you can also use the following options:

```js
var kmz = L.kmzLayer(null, {
  ballon: false, // disable default popup and tooltip.
  // bindPopup: false,
  // bindTooltip: false,
  geometryToLayer: function(data, xml) {
    let layer = this._geometryToLayer(data, xml);
    let el = xml.getElementsByTagName('BalloonStyle');
    layer.eachLayer( function(l) { /* you can bind your own ballon here */ } );
    return layer;
  }
});
```

**More info:**

- https://leafletjs.com/reference-1.6.0.html#popup
- https://leafletjs.com/reference-1.6.0.html#tooltip

_Happy coding,
Raruto_
