### ISSUE TITLE
Keep data up to date with network link KML (only usable online)

### ISSUE THREAD

**Issue by sncelta** [Raruto/leaflet-kmz#31]
I am trying to use the network link with your plugin and it gives an CORS error:

`Access to XMLHttpRequest at 'https://www.google.com/maps/d/u/8/kml?forcekml=1&mid=rest-of-link' from origin 'http://127.0.0.1' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`

> to be able to use Google files (eg. through Google My Maps) you MUST use a valid third-party kml proxy server

What is meant by "valid third-party kml proxy server"? Could you please elaborate?

Thanks in advance!

**Comment by Raruto** [comment]
Hi @sncelta,

I've never tried to use this network links, but I think you want to view a file hosted on a google server (eg. [Google MyMaps](https://mapsengine.google.com/map/)).

In this case the Google servers do not allow you to download the kmz / kml files directly from your browser (hence the reason for the CORS error), but you have to write a server-side script that downloads and returns that file (so your javascript XHR request will call your server instead of Google's ones, just like a proxy).

If you are on PHP, you can try to see [mcnemesis/proxy.php](https://github.com/mcnemesis/proxy.php) as a starting point to write your own script.

_Have a nice day,
Raruto_
