### ISSUE TITLE
Removing KMZ layer

### ISSUE THREAD

**Issue by macieksonik** [Raruto/leaflet-kmz#33]
I try to remove existing KMZ layer before loading a new one. 

```js
var kmz = L.kmzLayer();
map.addLayer(kmz);
kmz.load("file.kmz');
```

I think it should be also `kmz.remove()` option or perhaps someone knows how to remove it. 
`map.removeLayer(kmz)` doesn't work - there is no such layer...

**Comment by Raruto** [comment]
Hi Maciej,

as you can see [`L.KMZLayer`](https://github.com/Raruto/leaflet-kmz/blob/ed43fe930ddd93267278ad0c734ce699ecdd607a/src/KMZLayer.js#L3) extends [`L.FeatureGroup`](https://leafletjs.com/reference.html#featuregroup), if you try to call the two methods you mention above into the [demo](https://raruto.github.io/leaflet-kmz/examples/leaflet-kmz.html) they just work fine.

In your code it might not work because you are not waiting for the layers to be fully loaded:

https://github.com/Raruto/leaflet-kmz/blob/ed43fe930ddd93267278ad0c734ce699ecdd607a/src/KMZLayer.js#L57

check out this other comment to get an idea of how can you wait for that event: https://github.com/Raruto/leaflet-kmz/pull/21#issuecomment-1056865232

_Have a nice day,
Raruto_

**Comment by angela1393aa** [comment]
```js
componentDidUpdate(prevProps, prevState) {
  if (prevState.OnKMZ !== undefined && prevState.OnKMZ !== this.state.OnKMZ) {
      prevState.OnKMZ.remove(this.mymap);
  }
}

...
  
let kmz = L.kmzLayer().addTo(this.mymap);
  
kmz.load(this.props.OnKMZ);
  
this.setState({'OnKMZ':kmz});

...
```
