### ISSUE TITLE
missing folder infos

### ISSUE THREAD

**Issue by jayantpaliwal** [Raruto/leaflet-kmz#40]
While converting xml to geoJson using @tmcw/togeojson@4.1.0/dist/togeojson.umd.js is missing the folder infos.

```js
_parseKML: function(data, props) {
		var xml = _.toXML(data, props);
		var geojson = _.toGeoJSON(xml, props);
		var layer = (this.options.geometryToLayer || this._geometryToLayer).call(this, geojson, xml);
		this.addLayer(layer);
		this.fire('load', { layer: layer, name: geojson.properties.name });
	},
```

it merged all the folder layers
![image](https://github.com/Raruto/leaflet-kmz/assets/9565730/4a96444c-168b-4b91-818e-62d99cbf1ead)

I need to present the layers like google earth.

Folders-> Sub layers of folders 

![image](https://github.com/Raruto/leaflet-kmz/assets/9565730/3141c3a0-ecd8-4f6c-9bc2-a0237f6598d3)

**Comment by Raruto** [comment]
Hi @jayantpaliwal,

Javascript dependencies are lazy loaded only when not found on the page,

ie. a previous `<script src="@tmcw/togeojson@4.1.0/dist/togeojson.umd.js"></script>`:

https://github.com/Raruto/leaflet-kmz/blob/ed43fe930ddd93267278ad0c734ce699ecdd607a/src/KMZLayer.js#L140-L152

The version provided by this plugin is not mandatory, otherwise please propose your own PR.

👋 Raruto
